name: Test build kernel

on:
  push:
    branches:
      Grass
  pull_request:
    branches:
      Grass
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - device: m31
    name: "🚧 Build for ${{matrix.device}}"
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update
          bash <(curl https://gist.githubusercontent.com/roynatech2544/0feeeb35a6d1782b186990ff2a0b3657/raw/b170134a94dac3594df506716bc7b802add2724b/setup.sh)
          sudo apt install bison flex libssl-dev
          cp local.config.sample local.config
          echo "OBJ=arch/arm64/boot/Image" >> local.config

      - name: Run build
        run: |
          DEVICE=${{matrix.device}} bash build_kernel.sh

      - name: Upload to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: 4151668467
          token: 5712598673:AAGT0PhYTFl-_TZjF0MIqLoxZzK3LO66gh0
          document: scripts/packaging/Grass*.zip
          message: "Grass Build Completed"
